### ISSUE TITLE
Deleting rules retrieved with get_rules() errors out

### ISSUE THREAD

**Issue by j-bennet** [abh1nav/gnippy#9]
If I do this:

```
all_rules = rules.get_rules()
rules.delete_rules(all_rules)
```

I get an exception:

```
Traceback (most recent call last):
  File "configurator.py", line 93, in <module>
    delete_rules(popts.file_name)
  File "configurator.py", line 43, in delete_rules
    rules.delete_rules(all_rules)
  File "/Users/irina/.pyenv/versions/casterisk/lib/python2.7/site-packages/gnippy/rules.py", line 180, in delete_rules
    _delete(conf, rules_list)
  File "/Users/irina/.pyenv/versions/casterisk/lib/python2.7/site-packages/gnippy/rules.py", line 96, in _delete
    _check_rules_list(built_rules)
  File "/Users/irina/.pyenv/versions/casterisk/lib/python2.7/site-packages/gnippy/rules.py", line 50, in _check_rules_list
    fail()
  File "/Users/irina/.pyenv/versions/casterisk/lib/python2.7/site-packages/gnippy/rules.py", line 33, in fail
    raise RulesListFormatException(msg)
gnippy.errors.RulesListFormatException: rules_list is not in the correct format. Please use build_rule to build your rules list.
```

In my case, `all_rules` only contains one item and looks like this:

```
[{u'tag': None, u'value': u'url_contains:"mashable.com"'}]
```

It seems that {'tag'=None} is the problem when submitting to delete API. If my list looks like this:

```
[{u'value': u'url_contains:"mashable.com"'}]
```

then there's no exception and rules are deleted.

**Comment by abh1nav** [comment]
@j-bennet Thanks for reporting this! I've fixed it in the latest release. Please let me know if it still gives you trouble :smile:
